import { createResolver, defineNuxtModule, addTemplate, addTypeTemplate } from '@nuxt/kit'
import { readPackageJSON, type PackageJson } from 'pkg-types'
import { packageIsInstalled } from '../utils/meta'
import type { CapacitorConfig } from '@capacitor/cli'
import defu from 'defu'
import { withLeadingSlash, withoutTrailingSlash } from 'ufo'
import { existsSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { consola } from 'consola'
import { execSync } from 'node:child_process'

interface NuxtCapacitorOptions {
  autoSync?: boolean
  config?: CapacitorConfig
}

declare module '@nuxt/schema' {
  interface NuxtOptions {
    capacitor: NuxtCapacitorOptions
  }
}

const name = 'nuxt-capacitor'

export default defineNuxtModule<NuxtCapacitorOptions>({
  meta: {
    name,
    configKey: 'capacitor',
  },
  defaults: {
    autoSync: true,
    config: {
      appId: 'com.example.app',
      appName: 'Nuxt Capacitor',
    },
  },
  async setup(_options, nuxt) {
    const logger = consola.create({ defaults: { tag: name } })

    if (nuxt.options.dev) {
      const devHost = nuxt.options.devServer.host
      if (!devHost) {
        logger.warn('devServer.host is not set. This may cause issues with Capacitor. set with --host=0.0.0.0')
      }
      else if (devHost !== '0.0.0.0') {
        logger.warn('devServer.host is not set to 0.0.0.0. This may cause issues with Capacitor. Set with --host=0.0.0.0')
      }
    }

    const thisModuleDir = join(createResolver(import.meta.url).resolve('.'), '..')
    const rootDir = nuxt.options.rootDir
    const distPath = '.output/public'

    const meta = await readPackageJSON(rootDir).catch(() => ({} as PackageJson))
    const projectPkg = new Set([
      ...Object.keys(meta.dependencies ?? {}),
      ...Object.keys(meta.devDependencies ?? {}),
    ])

    if (!projectPkg.has('@capacitor/cli') && !(await packageIsInstalled('@capacitor/cli'))) {
      throw new Error('@capacitor/cli is not installed.')
    }

    nuxt.options.capacitor = defu(_options, nuxt.options.capacitor)

    // Inject dev server
    if (nuxt.options.dev) {
      logger.info('Using devServer.url for capacitor server config.')
      nuxt.options.capacitor.config = defu(nuxt.options.capacitor.config, {
        server: {
          url: nuxt.options.devServer.url,
          cleartext: true,
        },
      })
    }
    else {
      delete nuxt.options.capacitor.config?.server
    }

    // Fallback webDir
    nuxt.options.capacitor.config = defu(nuxt.options.capacitor.config, {
      webDir: withoutTrailingSlash(nuxt.options.rootDir) + withLeadingSlash(distPath),
    })

    const userConfigPath = join(rootDir, 'capacitor.config.ts')
    const userConfigExists = existsSync(userConfigPath)

    if (!userConfigExists && thisModuleDir !== rootDir) {
      const defaultUserConfig = [
        `import { defineCapacitorConfig } from './.nuxt/capacitor.mjs';`,
        ``,
        `export default defineCapacitorConfig({`,
        `  // Add your overrides here, or configure via nuxt.config.ts > capacitor: {}`,
        `});`,
      ].join('\n')

      writeFileSync(userConfigPath, defaultUserConfig, 'utf-8')
      logger.info(`Created default capacitor.config.ts in project root.`)
    }

    addTemplate({
      filename: 'capacitor.mjs',
      write: true,
      options: {
        config: nuxt.options?.capacitor?.config ?? {},
      },
      getContents: ({ options }) => {
        const finalConfig = JSON.stringify(options.config, null, 2)
        return [
          `/* Auto generated by ${name}. Do not edit. */`,
          `const _defaultConfig = ${finalConfig};`,
          ``,
          `/** @param {import('@capacitor/cli').CapacitorConfig} config */`,
          `export const defineCapacitorConfig = (config) => Object.assign({}, _defaultConfig, config);`,
        ].join('\n')
      },
    })

    addTypeTemplate({
      filename: 'capacitor.d.ts',
      write: true,
      getContents: () => {
        return [
          `import type { CapacitorConfig } from '@capacitor/cli';`,
          ``,
          `/**`,
          ` * Define your Capacitor config with full type safety.`,
          ` * Values are deeply merged over the defaults provided by ${name}.`,
          ` *`,
          ` * @param config - Partial CapacitorConfig overrides`,
          ` * @returns Fully merged CapacitorConfig`,
          ` */`,
          `export declare function defineCapacitorConfig(config: CapacitorConfig): CapacitorConfig;`,
        ].join('\n')
      },
    })

    // Auto sync
    if (nuxt.options.capacitor.autoSync) {
      //
      const requiredFile = `${distPath}/index.html`
      const capSync = (scope = 'listen') => async () => {
        if (!existsSync(join(rootDir, requiredFile))) {
          logger.warn(`No '${requiredFile}' found when attempting to cap sync on '${scope}'. This is critical for capacitor to work. Try with pnpm build --prerender`)
          return
        }
        try {
          execSync('npx cap sync', { stdio: 'inherit', cwd: rootDir })
          logger.success(`npx cap sync completed on ${scope}.`)
        }
        catch (err) {
          logger.error(err)
        }
      }

      //
      if (nuxt.options.dev) {
        nuxt.hook('listen', capSync('listen'))
        nuxt.hook('build:done', async () => {
          logger.info('🔨 Running generate for initial Capacitor assets...')
          try {
            execSync('npx nuxt build --prerender', { cwd: rootDir, stdio: 'ignore' })
            logger.success(`Generated static pages into ${distPath}`)
            await capSync('build:done')()
          }
          catch (err) {
            logger.error(err)
            return
          }
        })
      }
      else {
        nuxt.hook('nitro:build:public-assets', capSync('nitro:build:public-assets'))
      }
    }
  },
})
