import { createResolver, defineNuxtModule, addTemplate, addTypeTemplate } from '@nuxt/kit'
import { readPackageJSON, type PackageJson } from 'pkg-types'
import { packageIsInstalled } from '../utils/meta'
import type { CapacitorConfig } from '@capacitor/cli'
import defu from 'defu'
import { withoutTrailingSlash } from 'ufo'
import { existsSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

interface NuxtCapacitorOptions {
  config?: CapacitorConfig
}

declare module '@nuxt/schema' {
  interface NuxtOptions {
    capacitor: NuxtCapacitorOptions
  }
}

export default defineNuxtModule<NuxtCapacitorOptions>({
  meta: {
    name: 'nuxt-capacitor',
    configKey: 'capacitor',
  },
  defaults: {
    config: {
      appId: 'com.example.app',
      appName: 'Nuxt Capacitor',
      webDir: '.output/public',
    },
  },
  async setup(_options, nuxt) {
    const thisModuleDir = join(createResolver(import.meta.url).resolve('.'), '..')
    const rootDir = nuxt.options.rootDir
    const buildDir = nuxt.options.buildDir // .nuxt/

    const meta = await readPackageJSON(rootDir).catch(() => ({} as PackageJson))
    const projectPkg = new Set([
      ...Object.keys(meta.dependencies ?? {}),
      ...Object.keys(meta.devDependencies ?? {}),
    ])

    if (!projectPkg.has('@capacitor/cli') && !(await packageIsInstalled('@capacitor/cli'))) {
      throw new Error('@capacitor/cli is not installed.')
    }

    // Merge module defaults under nuxt.config capacitor options
    nuxt.options.capacitor = defu(nuxt.options.capacitor, _options)

    // Inject dev server
    if (nuxt.options.dev) {
      nuxt.options.capacitor.config = defu(nuxt.options.capacitor.config, {
        server: {
          url: nuxt.options.devServer.url,
          cleartext: true,
        },
      })
    }

    // Fallback webDir
    nuxt.options.capacitor.config = defu(nuxt.options.capacitor.config, {
      webDir: withoutTrailingSlash(nuxt.options.buildDir) + '/public',
    })

    // --- Step 2: Check for ROOT/capacitor.config.ts ---
    const userConfigPath = join(rootDir, 'capacitor.config.ts')
    const userConfigExists = existsSync(userConfigPath)

    if (!userConfigExists && thisModuleDir !== rootDir) {
      // Write a default capacitor.config.ts for the user
      const defaultUserConfig = [
        `import { defineCapacitorConfig } from './.nuxt/capacitor.mjs';`,
        ``,
        `export default defineCapacitorConfig({`,
        `  // Add your overrides here, or configure via nuxt.config.ts > capacitor: {}`,
        `});`,
      ].join('\n')

      writeFileSync(userConfigPath, defaultUserConfig, 'utf-8')
      console.info('[nuxt-capacitor] Created default capacitor.config.ts in project root.')
    }

    // --- Step 4: Re-write .nuxt/capacitor.mjs with the fully merged config ---
    // Now that user config has been merged in, update the template with final values
    addTemplate({
      filename: 'capacitor.mjs',
      write: true,
      getContents: () => {
        const finalConfig = JSON.stringify(nuxt.options.capacitor.config ?? {}, null, 2)
        return [
          '/* Auto generated by nuxt-capacitor. Do not edit. */',
          `const _defaultConfig = ${finalConfig};`,
          ``,
          `/** @param {import('@capacitor/cli').CapacitorConfig} config */`,
          `export const defineCapacitorConfig = (config) => Object.assign({}, _defaultConfig, config);`,
        ].join('\n')
      },
    })

    addTypeTemplate({
      filename: 'capacitor.d.ts',
      write: true,
      getContents: () => {
        return [
          `import type { CapacitorConfig } from '@capacitor/cli';`,
          ``,
          `/**`,
          ` * Define your Capacitor config with full type safety.`,
          ` * Values are deeply merged over the defaults provided by nuxt-capacitor.`,
          ` *`,
          ` * @param config - Partial CapacitorConfig overrides`,
          ` * @returns Fully merged CapacitorConfig`,
          ` */`,
          `export declare function defineCapacitorConfig(config: CapacitorConfig): CapacitorConfig;`,
        ].join('\n')
      },
    })
  },
})
