import { addTemplate, addTypeTemplate } from '@nuxt/kit'
import type { Nuxt } from '@nuxt/schema'
import type { CapacitorConfig } from '@capacitor/cli'
import { join } from 'node:path'
import { existsSync, writeFileSync, readFileSync } from 'node:fs'
import { defu } from 'defu'

const name = 'nuxt-capacitor'

const capacitorConfigFiles = ['capacitor.config.json', 'capacitor.config.ts', 'capacitor.config.mjs'] as const

export const hasAnyCapacitorConfigFile = (nuxt: Nuxt): typeof capacitorConfigFiles[number] | false => {
  for (const file of capacitorConfigFiles) {
    if (existsSync(join(nuxt.options.rootDir, file))) {
      return file
    }
  }
  return false
}
export const upsertCapacitorJsonConfig = async (nuxt: Nuxt) => {
  // @ts-expect-error Not typed...
  const config = (nuxt.options?.capacitor?.config || {}) as CapacitorConfig
  const configFile = join(nuxt.options.rootDir, 'capacitor.config.json')
  writeFileSync(configFile, JSON.stringify(config, null, 2), 'utf-8')
}

export const createCapacitorTsConfig = async (nuxt: Nuxt) => {
  const userConfigPath = join(nuxt.options.rootDir, 'capacitor.config.ts')

  const defaultUserConfig = [
    `import { defineCapacitorConfig } from './.nuxt/capacitor.mjs';`,
    ``,
    `export default defineCapacitorConfig({`,
    `  // Add your overrides here, or configure via nuxt.config.ts > capacitor: {}`,
    `});`,
  ].join('\n')

  writeFileSync(userConfigPath, defaultUserConfig, 'utf-8')
}

export const addCodeTemplates = (nuxt: Nuxt) => {
  addTemplate({
    filename: 'capacitor.mjs',
    write: true,
    options: {
      // @ts-expect-error Not typed...
      config: nuxt.options?.capacitor?.config ?? {},
    },
    getContents: ({ options }) => {
      const finalConfig = JSON.stringify(options.config, null, 2)
      return [
        `/* Auto generated by ${name}. Do not edit. */`,
        `const _defaultConfig = ${finalConfig};`,
        ``,
        `/** @param {import('@capacitor/cli').CapacitorConfig} config */`,
        `export const defineCapacitorConfig = (config) => Object.assign({}, _defaultConfig, config);`,
      ].join('\n')
    },
  })

  addTypeTemplate({
    filename: 'capacitor.d.ts',
    write: true,
    getContents: () => {
      return [
        `import type { CapacitorConfig } from '@capacitor/cli';`,
        ``,
        `/**`,
        ` * Define your Capacitor config with full type safety.`,
        ` * Values are deeply merged over the defaults provided by ${name}.`,
        ` *`,
        ` * @param config - Partial CapacitorConfig overrides`,
        ` * @returns Fully merged CapacitorConfig`,
        ` */`,
        `export declare function defineCapacitorConfig(config: CapacitorConfig): CapacitorConfig;`,
      ].join('\n')
    },
  })
}
